name: apewebsite
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  provider: ^6.1.4
  animated_text_kit: ^4.2.3
  country_icons: ^3.0.0
  url_strategy: ^0.3.0
  icons_plus: ^5.0.0
  url_launcher: ^6.3.1
  flutter_widget_from_html: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/home_page/
    - assets/logos/
    - assets/home_page/Education.png
    - assets/home_page/Alvdorf.png
    - assets/alverdorf_page/
    - assets/alverdorf_page/step/
